<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ElmishTodos.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="vendor/Router.fs" />
    <Compile Include="src/Api.fs" />
    <Compile Include="src/TodoPage.fs" />
    <Compile Include="src/App.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Fetch" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Fable.Elmish" />
    <PackageReference Include="Feliz" />
    <PackageReference Include="Feliz.UseElmish" />
    <ProjectReference Include="../ElmishTodos.Shared/ElmishTodos.Shared.fsproj" />
  </ItemGroup>

</Project>
