<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ElmishTodos.Client</RootNamespace>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="vendor/Router.fs" />
    <Compile Include="src/TodoPage.fs" />
    <Compile Include="src/App.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ElmishTodos.Shared/ElmishTodos.Shared.fsproj" />
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Fable.Elmish" />
    <PackageReference Include="Feliz" />
    <PackageReference Include="Feliz.UseElmish" />
    <PackageReference Include="Thoth.Json" />
  </ItemGroup>

</Project>
