<Project>
  <ItemGroup>
    <PackageVersion Include="FSharp.Core" Version="10.1.301" />
    <!-- Server -->
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.9" />
    <PackageVersion Include="Oxpecker" Version="2.0.1" />
    <PackageVersion Include="Oxpecker.OpenApi" Version="2.1.2" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.10" />
    <!-- Client -->
    <PackageVersion Include="Fable.Core" Version="5.2.0" />
    <PackageVersion Include="Fable.Elmish" Version="5.0.2" />
    <PackageVersion Include="Fable.Fetch" Version="2.7.0" />
    <PackageVersion Include="Feliz" Version="3.3.3" />
    <PackageVersion Include="Feliz.UseElmish" Version="5.0.0" />
    <PackageVersion Include="Thoth.Fetch" Version="3.0.1" />
    <PackageVersion Include="Thoth.Json" Version="10.5.1" />
    <!-- Shared -->
    <PackageVersion Include="Thoth.Json.Net" Version="12.0.0" />
  </ItemGroup>
</Project>
