<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LustreTodos.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <GenerateProgramFile>false</GenerateProgramFile>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TestApp.fs" />
    <Compile Include="TodosTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/LustreTodos/LustreTodos.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>

</Project>
