<Project>
  <ItemGroup>
    <PackageVersion Include="FSharp.Core" Version="10.1.302" />
    <!-- Server -->
    <PackageVersion Include="dbup-sqlite" Version="6.0.4" />
    <PackageVersion Include="FsToolkit.ErrorHandling" Version="5.2.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageVersion Include="Oxpecker.OpenApi" Version="2.1.2" />
    <PackageVersion Include="Oxpecker" Version="2.1.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.17" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="SqlHydra.Query" Version="4.0.4" />
    <PackageVersion Include="Thoth.Json.Net" Version="12.0.0" />
    <!-- Testing -->
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.10" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit" Version="2.9.3" />
  </ItemGroup>
</Project>
