<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ElmishTodos.Server</RootNamespace>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Auth.fs" />
    <Compile Include="Middleware.fs" />
    <Compile Include="OpenApi.fs" />
    <Compile Include="Todos.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <ProjectReference Include="../ElmishTodos.Shared/ElmishTodos.Shared.fsproj" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Oxpecker" />
    <PackageReference Include="Oxpecker.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Thoth.Json.Net" />
  </ItemGroup>

</Project>
