// This code was generated by `SqlHydra.Sqlite` -- v4.0.1.
namespace LustreTodos.Server.Db

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 0, 1)
    let ns = "LustreTodos.Server.Db"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type SchemaVersions =
        { SchemaVersionID: int64
          ScriptName: string
          Applied: System.DateTime }

    let SchemaVersions = table<SchemaVersions>

    [<CLIMutable>]
    type Todos =
        { Id: System.Guid
          UserId: string
          Title: string
          Completed: bool
          CreatedAt: int64 }

    let Todos = table<Todos>


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
